name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: actions/checkout@v4

      # Step to install dependencies
      - name: Install dependencies
        run: npm install

      # Step to debug current directory
      - name: Debug current directory
        run: ls -al

      # Step to debug node_modules directory
      - name: Debug node_modules directory
        run: ls -al node_modules

      - run: npm run build

      # Updated action to use Node.js 20
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BRANDON_LARSEN_PORTFOLIO }}'
          channelId: live
          projectId: brandon-larsen-portfolio
